UKHomeOffice/callisto-ui

src/components/layout/header/Header.jsx, src/components/layout/header/HomeOfficeLogo.jsx, src/components/layout/header/SignIn.jsx
These changes will fix the alignment of the header for callisto.~
**BEFORE**
**AFTER**
=> Fix header align with margins and logo view box

src/components/common/form/error-summary/ErrorSummary.jsx, src/components/common/form/error-summary/ErrorSummary.spec.jsx, src/components/timecard/edit-shift-hours/EditShiftHours.jsx, src/components/timecard/select-timecard-period-type/SelectTimecardPeriodType.jsx, src/pages/timecard/Timecard.spec.jsx
Added functionality to focus on summary errors when they appear
=> EAHW-2149 Focus on Summary Errors

mocks/mockData.js, src/components/timecard/edit-shift-hours/EditShiftHours.jsx, src/components/timecard/edit-shift-hours/EditShiftHours.spec.jsx
- Update `EditShiftHours` to set timecard context using response from api call
- Create mock object `shiftTimeEntryWithoutFinishTime` for testing
- Add tests
=> EAHW-926: Auto insert colon

mocks/apiServer.js, mocks/mockData.js, src/components/timecard/simple-time-period/SimpleTimePeriod.jsx, src/components/timecard/simple-time-period/SimpleTimePeriod.spec.jsx, src/pages/timecard/Timecard.jsx, src/pages/timecard/Timecard.spec.jsx
Added support for Non-working days
Changed Scheduled Rest Day to more generic SimpleTimePeriod component
=> Eahw 1349 add non working day

package-lock.json, package.json, src/App.jsx, src/components/error/ApplicationError.jsx, src/components/error/ErrorBoundary.jsx, src/components/error/ServiceError.jsx, src/components/error/error-boundary/ErrorBoundary.jsx, src/components/error/error-boundary/ErrorBoundary.spec.jsx, src/components/timecard/edit-shift-hours/EditShiftHours.jsx, src/components/timecard/edit-shift-hours/EditShiftHours.spec.jsx, src/components/timecard/edit-shift-timecard/EditShiftTimecard.jsx, src/components/timecard/edit-shift-timecard/EditShiftTimecard.spec.jsx, src/components/timecard/simple-time-period/SimpleTimePeriod.jsx, src/components/timecard/simple-time-period/SimpleTimePeriod.spec.jsx, src/context/ApplicationContext.jsx, src/pages/timecard/Timecard.jsx, src/pages/timecard/Timecard.spec.jsx, src/test/helpers/TimecardContext.jsx, src/utils/api-utils/ApiUtils.js, src/utils/api-utils/ApiUtils.spec.js
- Adds error handling to the UI as a whole and covers handling errors from server responses.
- React error boundary wrapping entire app to auto handle application bugs.
- Using app context to hold a flag for there being an error caused by the API which gets lifted up to the error boundary (as react error boundaries do not handle errors thrown within async blocks).
Error message presented when caused by the UI itself (blocks out all other components):
Error message presented when caused by the API (Allows other components to still show):
=> Feature/eahw-2188: Handle unexpected errors in UI

README.md, src/pages/Home.jsx
- Remove the Accruals api call from the homepage
- Small ReadMe update to explain mixing mock and actual data
=> Eahw 2248/remove accruals api call

.drone.yml
- Add qualitygate wait parameter which fixes the issue where the quality gate fails but the build succeeds
- Ignore running sonar scans on PR - run on everything else
=> Eahw 2190/sonar add wait quality gate

src/context/ApplicationContext.jsx
moved ownerid and timecardClaim setters to variable initialisation
=> Fix owner Id not being set in certain situations

mocks/mockData.js, src/pages/timecard/Timecard.jsx, src/utils/api-utils/UrlSearchParamBuilder.js, src/utils/api-utils/urlSearchParamBuilder.spec.js, src/utils/filters/resource-filter-builder/resourceFilterBuilder.js, src/utils/filters/resource-filter-builder/resourceFilterBuilder.spec.js, src/utils/filters/time-entry-filter/timeEntryFilterBuilder.js, src/utils/filters/time-entry-filter/timeEntryFilterBuilder.spec.js
This PR is to address the filter functionality required for eahw-589.
The requirement is to show time entries that cover two days to show on the day they start and on the day they end.
=> Eahw 589 fix the api filter functionality

src/App.jsx, src/components/layout/header/Header.jsx
Move skip link into Header component to fix accessibility issue picked up by Axe scanner (more details on ticket [here](https://collaboration.homeoffice.gov.uk/jira/browse/EAHW-2361))
=> EAHW-2361: Accessibility fix

.drone.yml
- Add 'promote to test check' to ensure build being promoted is on the main branch
- Remove commit message on git tag
- [Example branch promotion failing the check](https://drone-gh.acp.homeoffice.gov.uk/UKHomeOffice/callisto-ui/843)
=> Eahw 2429/promote UI test

.drone.yml
Adds the Prod deploy steps to the UI project.
- Checks the build being promoted was successful and pushed to main branch
- Builds for prod and uploads to S3
- Added a Dev Url check (Test and Prod url checks to follow)
- Slack message fix and add build link
=> Eahw 2441/promote UI prod

.github/workflows/docker.yaml, default.conf, dockerfile
Using a GitHub action to create a docker image with the build react app served from an nginx container.
Builds on main and branches containing the JIRA project code EAHW. 
Main is tagged with latest and anything matching the JIRA project code will be tagged with the issue number.
=> Add docker file and GitHub workflow to produce docker image

.env, .gitignore, README.md, default.conf, docker-compose.yml, package.json, vite.config.js
Removed temp and not required files
=> LocalDev - UI solution

.drone.yml, src/utils/time-entry-utils/timeEntryUtils.spec.js
- Added Slack notifications for #callisto-urgent-tech-notifications channel
- Updated original tech notifications by adding Drone build link
- Run linting on file
=> EAHW-2347: Urgent slack alerts

.drone.yml
Added step to pipeline to exit when branch is main
=> EAHW-2347: Test urgent notifications

src/components/timecard/edit-shift-timecard/EditShiftTimecard.jsx, src/components/timecard/simple-time-period/SimpleTimePeriod.jsx, src/context/ApplicationContext.jsx, src/pages/timecard/Timecard.jsx, src/utils/api-utils/ApiUtils.js, src/utils/api-utils/ApiUtils.spec.js
- set irrecoverable error to be the default 
- save and delete are recoverable 
- tidy up
=> Eahw 2252 error handling

.drone.yml
- Created a new build step for branch deploys which uses a new keycloak url
- Moved the deploy branch to S3 step into the branch deployment pipeline
Note: Keycloak realm and client ID for branches use the same values as the dev environment
=> Eahw 2589/keycloak branch deploys

README.md
Updating troubleshooting section of the readme for failing tests
=> Updating UI Readme

src/pages/timecard/Timecard.jsx, src/pages/timecard/Timecard.spec.jsx
Changes behaviour of timecard to return to the time period type selection screen when all time entries are removed
=> Eahw 1677/show time period type select when no time period

src/components/timecard/edit-shift/EditShift.jsx, src/components/timecard/shift/Shift.jsx, src/components/timecard/simple-time-period/SimpleTimePeriod.jsx
Fixing async processing in Timecard
=> Fixing async processing in Timecard

src/components/timecard/edit-shift/EditShift.jsx, src/components/timecard/select-timecard-period-type/SelectTimecardPeriodType.jsx
Disable sonar checks for on submit
=> Disable sonar checks for on submit

src/components/timecard/edit-shift/EditShift.jsx, src/components/timecard/select-timecard-period-type/SelectTimecardPeriodType.jsx
Disable sonar for whole return block
=> Disable sonar for whole return block

src/components/timecard/edit-shift/EditShift.jsx, src/components/timecard/select-timecard-period-type/SelectTimecardPeriodType.jsx
=> Undoing sonar changes

src/documents/accruals.md, src/pages/accruals/Accruals.jsx
Correct typo and removed unused field
=> Correct typo and removed unused field
